name: google_ml_kit

version: 0.7.3


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependency_overrides:
  firebase_messaging_platform_interface: 3.4.0
  firebase_crashlytics_platform_interface: 3.1.13
  cloud_firestore_platform_interface: 5.5.5
  firebase_auth_platform_interface: 6.1.2
  firebase_storage_platform_interface: 4.0.14
  cloud_functions_platform_interface: 5.0.21
  firebase_analytics_platform_interface: 3.0.5
  firebase_remote_config_platform_interface: 1.0.5
  firebase_dynamic_links_platform_interface: 0.2.0+5
  firebase_performance_platform_interface: 0.1.0+5
  firebase_app_installations_platform_interface: 0.1.0+6

dependencies:
  flutter:
    sdk: flutter
  dropdown_search:
  firebase_auth:
  firebase_core:
  google_sign_in: ^5.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  image_path: "/assets/ic_launcher.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.google_ml_kit
        pluginClass: GoogleMlKitPlugin
      ios:
        pluginClass: GoogleMlKitPlugin

